-- Project B full-catalog review (catalog-full-review).
-- Reviewed the 469 never-flagged rows that B1 left is_verified=false:
-- 428 confirmed correct, 39 corrected, 2 held ambiguous.
-- This migration applies the 39 PRIMARY corrections to envs where the B1 seed
-- already ran (the regenerated 20260604120200 seed bakes the same corrections in
-- for fresh resets via build-seed.ts primary-overrides.json), then promotes all
-- 467 reviewed-correct rows to is_verified=true. Held rows stay is_verified=false.
-- Idempotent; guarded on source='free-exercise-db' so it never touches
-- user- or system-authored rows. Folds under R-27 (Project B); no new R-id/D-id.
-- Corrections use codes the coarse->fine mapper cannot emit (obliques/full_body/
-- tibialis) plus disambiguation fixes the fixed-precedence mapper got wrong.

-- 1) primary-tag corrections (39 rows)
update public.exercises e
set primary_muscles = v.prim
from (values
  ('Alternating_Kettlebell_Row', array['lat']::text[]),
  ('Anterior_Tibialis-SMR', array['tibialis']::text[]),
  ('Anti-Gravity_Press', array['delt_rear']::text[]),
  ('Bear_Crawl_Sled_Drags', array['full_body']::text[]),
  ('Bent_Over_Low-Pulley_Side_Lateral', array['delt_rear']::text[]),
  ('Cable_Hip_Adduction', array['adductors']::text[]),
  ('Cuban_Press', array['delt_rear','delt_side']::text[]),
  ('Dumbbell_Lying_One-Arm_Rear_Lateral_Raise', array['delt_rear']::text[]),
  ('Dumbbell_Lying_Rear_Lateral_Raise', array['delt_rear']::text[]),
  ('Incline_Bench_Pull', array['delt_rear','rhomboids']::text[]),
  ('Incline_Push-Up', array['pec_lower']::text[]),
  ('Incline_Push-Up_Depth_Jump', array['pec_lower']::text[]),
  ('Incline_Push-Up_Medium', array['pec_lower']::text[]),
  ('Incline_Push-Up_Wide', array['pec_lower']::text[]),
  ('Inverted_Row', array['lat']::text[]),
  ('Inverted_Row_with_Straps', array['lat']::text[]),
  ('Iron_Crosses_stretch', array['obliques']::text[]),
  ('Knee_Circles', array['quads']::text[]),
  ('Leverage_High_Row', array['lat']::text[]),
  ('Linear_3-Part_Start_Technique', array['full_body']::text[]),
  ('Linear_Acceleration_Wall_Drill', array['full_body']::text[]),
  ('Linear_Depth_Jump', array['full_body']::text[]),
  ('Middle_Back_Stretch', array['obliques']::text[]),
  ('Mixed_Grip_Chin', array['lat']::text[]),
  ('Mountain_Climbers', array['abs_lower']::text[]),
  ('One_Arm_Chin-Up', array['lat']::text[]),
  ('One-Arm_Dumbbell_Row', array['lat']::text[]),
  ('One-Arm_Kettlebell_Para_Press', array['delt_side']::text[]),
  ('One-Arm_Kettlebell_Row', array['lat']::text[]),
  ('One-Arm_Long_Bar_Row', array['lat']::text[]),
  ('Overhead_Slam', array['full_body']::text[]),
  ('Power_Clean_from_Blocks', array['full_body']::text[]),
  ('Rear_Leg_Raises', array['glutes']::text[]),
  ('Ring_Dips', array['pec_lower','tri_lateral']::text[]),
  ('Standing_Barbell_Press_Behind_Neck', array['delt_side']::text[]),
  ('Standing_Bradford_Press', array['delt_side']::text[]),
  ('Standing_Two-Arm_Overhead_Throw', array['full_body']::text[]),
  ('Wide-Grip_Decline_Barbell_Pullover', array['lat']::text[]),
  ('Windmills', array['obliques']::text[])
) as v(external_id, prim)
where e.external_id = v.external_id and e.source = 'free-exercise-db';

-- 2) verify the 467 reviewed-correct rows (428 confirmed + 39 corrected).
-- Held/ambiguous rows + the already-reviewed #160 set are unaffected here.
update public.exercises
set is_verified = true
where source = 'free-exercise-db' and external_id in (
  '90_90_Hamstring',
  'Adductor',
  'Adductor_Groin',
  'All_Fours_Quad_Stretch',
  'Alternate_Hammer_Curl',
  'Alternate_Incline_Dumbbell_Curl',
  'Alternating_Cable_Shoulder_Press',
  'Alternating_Kettlebell_Press',
  'Alternating_Kettlebell_Row',
  'Ankle_Circles',
  'Ankle_On_The_Knee',
  'Anterior_Tibialis-SMR',
  'Anti-Gravity_Press',
  'Arnold_Dumbbell_Press',
  'Balance_Board',
  'Band_Assisted_Pull-Up',
  'Band_Good_Morning',
  'Band_Good_Morning_Pull_Through',
  'Band_Hip_Adductions',
  'Band_Skull_Crusher',
  'Barbell_Curl',
  'Barbell_Curls_Lying_Against_An_Incline',
  'Barbell_Glute_Bridge',
  'Barbell_Hack_Squat',
  'Barbell_Hip_Thrust',
  'Barbell_Incline_Bench_Press_-_Medium_Grip',
  'Barbell_Lunge',
  'Barbell_Rear_Delt_Row',
  'Barbell_Seated_Calf_Raise',
  'Barbell_Shoulder_Press',
  'Barbell_Shrug',
  'Barbell_Shrug_Behind_The_Back',
  'Barbell_Side_Split_Squat',
  'Barbell_Walking_Lunge',
  'Bear_Crawl_Sled_Drags',
  'Bench_Dips',
  'Bench_Jump',
  'Bench_Sprint',
  'Bent_Over_Barbell_Row',
  'Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench',
  'Bent_Over_Low-Pulley_Side_Lateral',
  'Bent_Over_Two-Arm_Long_Bar_Row',
  'Bent_Over_Two-Dumbbell_Row',
  'Bent_Over_Two-Dumbbell_Row_With_Palms_In',
  'Bicycling',
  'Bicycling_Stationary',
  'Bodyweight_Mid_Row',
  'Bodyweight_Squat',
  'Bodyweight_Walking_Lunge',
  'Bottoms-Up_Clean_From_The_Hang_Position',
  'Brachialis-SMR',
  'Bradford_Rocky_Presses',
  'Butt_Lift_Bridge',
  'Cable_Hammer_Curls_-_Rope_Attachment',
  'Cable_Hip_Adduction',
  'Cable_Incline_Pushdown',
  'Cable_Lying_Triceps_Extension',
  'Cable_Preacher_Curl',
  'Cable_Rear_Delt_Fly',
  'Cable_Reverse_Crunch',
  'Cable_Rope_Overhead_Triceps_Extension',
  'Cable_Rope_Rear-Delt_Rows',
  'Cable_Seated_Lateral_Raise',
  'Cable_Shoulder_Press',
  'Cable_Shrugs',
  'Calf-Machine_Shoulder_Shrug',
  'Calf_Press',
  'Calf_Press_On_The_Leg_Press_Machine',
  'Calf_Raise_On_A_Dumbbell',
  'Calf_Raises_-_With_Bands',
  'Calf_Stretch_Elbows_Against_Wall',
  'Calf_Stretch_Hands_Against_Wall',
  'Calves-SMR',
  'Cat_Stretch',
  'Catch_and_Overhead_Throw',
  'Chair_Leg_Extended_Stretch',
  'Chair_Lower_Back_Stretch',
  'Chair_Squat',
  'Childs_Pose',
  'Chin-Up',
  'Chin_To_Chest_Stretch',
  'Clean_Shrug',
  'Close-Grip_EZ-Bar_Curl_with_Band',
  'Close-Grip_EZ_Bar_Curl',
  'Close-Grip_Front_Lat_Pulldown',
  'Close-Grip_Standing_Barbell_Curl',
  'Concentration_Curls',
  'Cross_Body_Hammer_Curl',
  'Cuban_Press',
  'Dancers_Stretch',
  'Decline_Barbell_Bench_Press',
  'Decline_Close-Grip_Bench_To_Skull_Crusher',
  'Decline_Dumbbell_Bench_Press',
  'Decline_Dumbbell_Flyes',
  'Decline_Push-Up',
  'Decline_Reverse_Crunch',
  'Decline_Smith_Press',
  'Dip_Machine',
  'Dips_-_Triceps_Version',
  'Donkey_Calf_Raises',
  'Double_Kettlebell_Push_Press',
  'Downward_Facing_Balance',
  'Drag_Curl',
  'Dumbbell_Alternate_Bicep_Curl',
  'Dumbbell_Bicep_Curl',
  'Dumbbell_Lunges',
  'Dumbbell_Lying_One-Arm_Rear_Lateral_Raise',
  'Dumbbell_Lying_Pronation',
  'Dumbbell_Lying_Rear_Lateral_Raise',
  'Dumbbell_Lying_Supination',
  'Dumbbell_One-Arm_Shoulder_Press',
  'Dumbbell_Prone_Incline_Curl',
  'Dumbbell_Rear_Lunge',
  'Dumbbell_Seated_Box_Jump',
  'Dumbbell_Seated_One-Leg_Calf_Raise',
  'Dumbbell_Shoulder_Press',
  'Dumbbell_Shrug',
  'Dumbbell_Step_Ups',
  'Dynamic_Back_Stretch',
  'EZ-Bar_Curl',
  'EZ-Bar_Skullcrusher',
  'Elevated_Back_Lunge',
  'Elevated_Cable_Rows',
  'Elliptical_Trainer',
  'Face_Pull',
  'Flat_Bench_Lying_Leg_Raise',
  'Flexor_Incline_Dumbbell_Curls',
  'Floor_Glute-Ham_Raise',
  'Flutter_Kicks',
  'Foot-SMR',
  'Freehand_Jump_Squat',
  'Frog_Hops',
  'Front_Barbell_Squat',
  'Front_Barbell_Squat_To_A_Bench',
  'Front_Leg_Raises',
  'Front_Squat_Clean_Grip',
  'Front_Squats_With_Two_Kettlebells',
  'Full_Range-Of-Motion_Lat_Pulldown',
  'Gironda_Sternum_Chins',
  'Glute_Ham_Raise',
  'Glute_Kickback',
  'Good_Morning',
  'Good_Morning_off_Pins',
  'Groin_and_Back_Stretch',
  'Groiners',
  'Hack_Squat',
  'Hammer_Curls',
  'Hammer_Grip_Incline_DB_Bench_Press',
  'Hamstring-SMR',
  'Hamstring_Stretch',
  'Hanging_Bar_Good_Morning',
  'Hanging_Leg_Raise',
  'Hanging_Pike',
  'High_Cable_Curls',
  'Hip_Circles_prone',
  'Hip_Extension_with_Bands',
  'Hip_Flexion_with_Band',
  'Hip_Lift_with_Band',
  'Hug_A_Ball',
  'Hug_Knees_To_Chest',
  'Hyperextensions_Back_Extensions',
  'Hyperextensions_With_No_Hyperextension_Bench',
  'IT_Band_and_Glute_Stretch',
  'Iliotibial_Tract-SMR',
  'Inchworm',
  'Incline_Bench_Pull',
  'Incline_Cable_Chest_Press',
  'Incline_Cable_Flye',
  'Incline_Dumbbell_Bench_With_Palms_Facing_In',
  'Incline_Dumbbell_Curl',
  'Incline_Dumbbell_Flyes',
  'Incline_Dumbbell_Flyes_-_With_A_Twist',
  'Incline_Dumbbell_Press',
  'Incline_Hammer_Curls',
  'Incline_Inner_Biceps_Curl',
  'Incline_Push-Up',
  'Incline_Push-Up_Depth_Jump',
  'Incline_Push-Up_Medium',
  'Incline_Push-Up_Reverse_Grip',
  'Incline_Push-Up_Wide',
  'Intermediate_Groin_Stretch',
  'Intermediate_Hip_Flexor_and_Quad_Stretch',
  'Inverted_Row',
  'Inverted_Row_with_Straps',
  'Iron_Crosses_stretch',
  'Isometric_Neck_Exercise_-_Front_And_Back',
  'Isometric_Neck_Exercise_-_Sides',
  'Jerk_Dip_Squat',
  'Jogging_Treadmill',
  'Kettlebell_Arnold_Press',
  'Kettlebell_One-Legged_Deadlift',
  'Kettlebell_Seated_Press',
  'Kettlebell_Seesaw_Press',
  'Knee_Across_The_Body',
  'Knee_Circles',
  'Kneeling_Forearm_Stretch',
  'Kneeling_High_Pulley_Row',
  'Kneeling_Hip_Flexor',
  'Kneeling_Jump_Squat',
  'Kneeling_Single-Arm_High_Pulley_Row',
  'Kneeling_Squat',
  'Lateral_Raise_-_With_Bands',
  'Latissimus_Dorsi-SMR',
  'Leg-Up_Hamstring_Stretch',
  'Leg_Extensions',
  'Leg_Lift',
  'Leg_Press',
  'Leverage_Deadlift',
  'Leverage_Decline_Chest_Press',
  'Leverage_High_Row',
  'Leverage_Incline_Chest_Press',
  'Leverage_Iso_Row',
  'Leverage_Shoulder_Press',
  'Leverage_Shrug',
  'Linear_3-Part_Start_Technique',
  'Linear_Acceleration_Wall_Drill',
  'Linear_Depth_Jump',
  'London_Bridges',
  'Looking_At_Ceiling',
  'Lower_Back-SMR',
  'Lunge_Pass_Through',
  'Lunge_Sprint',
  'Lying_Bent_Leg_Groin',
  'Lying_Cable_Curl',
  'Lying_Cambered_Barbell_Row',
  'Lying_Close-Grip_Bar_Curl_On_High_Pulley',
  'Lying_Close-Grip_Barbell_Triceps_Extension_Behind_The_Head',
  'Lying_Close-Grip_Barbell_Triceps_Press_To_Chin',
  'Lying_Crossover',
  'Lying_Dumbbell_Tricep_Extension',
  'Lying_Face_Down_Plate_Neck_Resistance',
  'Lying_Face_Up_Plate_Neck_Resistance',
  'Lying_Glute',
  'Lying_Hamstring',
  'Lying_High_Bench_Barbell_Curl',
  'Lying_Machine_Squat',
  'Lying_One-Arm_Lateral_Raise',
  'Lying_Prone_Quadriceps',
  'Lying_Rear_Delt_Raise',
  'Lying_Supine_Dumbbell_Curl',
  'Lying_T-Bar_Row',
  'Lying_Triceps_Press',
  'Machine_Bicep_Curl',
  'Machine_Preacher_Curls',
  'Machine_Shoulder_Military_Press',
  'Middle_Back_Shrug',
  'Middle_Back_Stretch',
  'Mixed_Grip_Chin',
  'Monster_Walk',
  'Mountain_Climbers',
  'Moving_Claw_Series',
  'Narrow_Stance_Hack_Squats',
  'Narrow_Stance_Leg_Press',
  'Natural_Glute_Ham_Raise',
  'Neck-SMR',
  'Olympic_Squat',
  'On-Your-Back_Quad_Stretch',
  'On_Your_Side_Quad_Stretch',
  'One-Arm_Dumbbell_Row',
  'One-Arm_Incline_Lateral_Raise',
  'One-Arm_Kettlebell_Military_Press_To_The_Side',
  'One-Arm_Kettlebell_Para_Press',
  'One-Arm_Kettlebell_Push_Press',
  'One-Arm_Kettlebell_Row',
  'One-Arm_Long_Bar_Row',
  'One-Arm_Side_Laterals',
  'One-Legged_Cable_Kickback',
  'One_Arm_Against_Wall',
  'One_Arm_Chin-Up',
  'One_Arm_Dumbbell_Preacher_Curl',
  'One_Arm_Lat_Pulldown',
  'One_Half_Locust',
  'One_Handed_Hang',
  'One_Knee_To_Chest',
  'One_Leg_Barbell_Squat',
  'Overhead_Cable_Curl',
  'Overhead_Lat',
  'Overhead_Slam',
  'Overhead_Triceps',
  'Parallel_Bar_Dip',
  'Pelvic_Tilt_Into_Bridge',
  'Peroneals-SMR',
  'Peroneals_Stretch',
  'Physioball_Hip_Bridge',
  'Piriformis-SMR',
  'Plate_Pinch',
  'Platform_Hamstring_Slides',
  'Posterior_Tibialis_Stretch',
  'Power_Clean_from_Blocks',
  'Preacher_Curl',
  'Preacher_Hammer_Dumbbell_Curl',
  'Prone_Manual_Hamstring',
  'Pull_Through',
  'Pullups',
  'Push_Press',
  'Pyramid',
  'Quad_Stretch',
  'Quadriceps-SMR',
  'Quick_Leap',
  'Rear_Leg_Raises',
  'Recumbent_Bike',
  'Reverse_Barbell_Curl',
  'Reverse_Barbell_Preacher_Curls',
  'Reverse_Cable_Curl',
  'Reverse_Crunch',
  'Reverse_Flyes',
  'Reverse_Flyes_With_External_Rotation',
  'Reverse_Grip_Bent-Over_Rows',
  'Reverse_Grip_Triceps_Pushdown',
  'Reverse_Hyperextension',
  'Reverse_Machine_Flyes',
  'Reverse_Plate_Curls',
  'Rhomboids-SMR',
  'Ring_Dips',
  'Rocket_Jump',
  'Rocking_Standing_Calf_Raise',
  'Rocky_Pull-Ups_Pulldowns',
  'Romanian_Deadlift',
  'Rope_Jumping',
  'Rope_Straight-Arm_Pulldown',
  'Runners_Stretch',
  'Running_Treadmill',
  'Scapular_Pull-Up',
  'Scissors_Jump',
  'Seated_Barbell_Military_Press',
  'Seated_Bent-Over_Rear_Delt_Raise',
  'Seated_Biceps',
  'Seated_Cable_Rows',
  'Seated_Cable_Shoulder_Press',
  'Seated_Calf_Raise',
  'Seated_Calf_Stretch',
  'Seated_Close-Grip_Concentration_Barbell_Curl',
  'Seated_Dumbbell_Curl',
  'Seated_Dumbbell_Inner_Biceps_Curl',
  'Seated_Dumbbell_Press',
  'Seated_Floor_Hamstring_Stretch',
  'Seated_Glute',
  'Seated_Good_Mornings',
  'Seated_Hamstring',
  'Seated_Hamstring_and_Calf_Stretch',
  'Seated_Head_Harness_Neck_Resistance',
  'Seated_One-arm_Cable_Pulley_Rows',
  'Seated_Side_Lateral_Raise',
  'See-Saw_Press_Alternating_Side_Press',
  'Shotgun_Row',
  'Shoulder_Press_-_With_Bands',
  'Side-Lying_Floor_Stretch',
  'Side_Lateral_Raise',
  'Side_Laterals_to_Front_Raise',
  'Side_Leg_Raises',
  'Side_Lying_Groin_Stretch',
  'Side_Neck_Stretch',
  'Side_Standing_Long_Jump',
  'Single-Cone_Sprint_Drill',
  'Single-Leg_High_Box_Squat',
  'Single-Leg_Leg_Extension',
  'Single_Leg_Butt_Kick',
  'Single_Leg_Glute_Bridge',
  'Single_Leg_Push-off',
  'Sit_Squats',
  'Sled_Drag_-_Harness',
  'Sled_Overhead_Backward_Walk',
  'Sled_Overhead_Triceps_Extension',
  'Sled_Reverse_Flye',
  'Sled_Row',
  'Smith_Machine_Behind_the_Back_Shrug',
  'Smith_Machine_Bent_Over_Row',
  'Smith_Machine_Calf_Raise',
  'Smith_Machine_Decline_Press',
  'Smith_Machine_Incline_Bench_Press',
  'Smith_Machine_Leg_Press',
  'Smith_Machine_Overhead_Shoulder_Press',
  'Smith_Machine_Pistol_Squat',
  'Smith_Machine_Reverse_Calf_Raises',
  'Smith_Machine_Stiff-Legged_Deadlift',
  'Smith_Machine_Upright_Row',
  'Smith_Single-Leg_Split_Squat',
  'Snatch_Shrug',
  'Speed_Band_Overhead_Triceps',
  'Speed_Box_Squat',
  'Spider_Curl',
  'Split_Jump',
  'Split_Squat_with_Dumbbells',
  'Split_Squats',
  'Stairmaster',
  'Standing_Alternating_Dumbbell_Press',
  'Standing_Barbell_Calf_Raise',
  'Standing_Barbell_Press_Behind_Neck',
  'Standing_Biceps_Cable_Curl',
  'Standing_Biceps_Stretch',
  'Standing_Bradford_Press',
  'Standing_Calf_Raises',
  'Standing_Concentration_Curl',
  'Standing_Dumbbell_Calf_Raise',
  'Standing_Dumbbell_Press',
  'Standing_Dumbbell_Reverse_Curl',
  'Standing_Dumbbell_Upright_Row',
  'Standing_Elevated_Quad_Stretch',
  'Standing_Gastrocnemius_Calf_Stretch',
  'Standing_Hamstring_and_Calf_Stretch',
  'Standing_Hip_Circles',
  'Standing_Hip_Flexors',
  'Standing_Inner-Biceps_Curl',
  'Standing_Long_Jump',
  'Standing_Military_Press',
  'Standing_Olympic_Plate_Hand_Squeeze',
  'Standing_One-Arm_Cable_Curl',
  'Standing_One-Arm_Dumbbell_Curl_Over_Incline_Bench',
  'Standing_Overhead_Barbell_Triceps_Extension',
  'Standing_Palm-In_One-Arm_Dumbbell_Press',
  'Standing_Palms-In_Dumbbell_Press',
  'Standing_Pelvic_Tilt',
  'Standing_Soleus_And_Achilles_Stretch',
  'Standing_Toe_Touches',
  'Standing_Two-Arm_Overhead_Throw',
  'Step-up_with_Knee_Raise',
  'Step_Mill',
  'Stiff-Legged_Barbell_Deadlift',
  'Stiff-Legged_Dumbbell_Deadlift',
  'Stiff_Leg_Barbell_Good_Morning',
  'Straight-Arm_Pulldown',
  'Straight_Bar_Bench_Mid_Rows',
  'Superman',
  'Suspended_Reverse_Crunch',
  'Suspended_Row',
  'T-Bar_Row_with_Handle',
  'The_Straddle',
  'Thigh_Abductor',
  'Thigh_Adductor',
  'Trail_Running_Walking',
  'Trap_Bar_Deadlift',
  'Tricep_Dumbbell_Kickback',
  'Triceps_Overhead_Extension_with_Rope',
  'Triceps_Pushdown',
  'Triceps_Pushdown_-_Rope_Attachment',
  'Triceps_Pushdown_-_V-Bar_Attachment',
  'Two-Arm_Dumbbell_Preacher_Curl',
  'Two-Arm_Kettlebell_Military_Press',
  'Two-Arm_Kettlebell_Row',
  'Underhand_Cable_Pulldowns',
  'Upper_Back-Leg_Grab',
  'Upper_Back_Stretch',
  'Upright_Cable_Row',
  'Upright_Row_-_With_Bands',
  'V-Bar_Pulldown',
  'V-Bar_Pullup',
  'Walking_Treadmill',
  'Weighted_Ball_Hyperextension',
  'Weighted_Bench_Dip',
  'Weighted_Pull_Ups',
  'Weighted_Sissy_Squat',
  'Weighted_Squat',
  'Wide-Grip_Decline_Barbell_Bench_Press',
  'Wide-Grip_Decline_Barbell_Pullover',
  'Wide-Grip_Lat_Pulldown',
  'Wide-Grip_Pulldown_Behind_The_Neck',
  'Wide-Grip_Rear_Pull-Up',
  'Wide-Grip_Standing_Barbell_Curl',
  'Wide_Stance_Stiff_Legs',
  'Windmills',
  'Worlds_Greatest_Stretch',
  'Wrist_Circles',
  'Wrist_Roller',
  'Wrist_Rotations_with_Straight_Bar',
  'Zercher_Squats',
  'Zottman_Curl',
  'Zottman_Preacher_Curl'
);
