-- Project B1 catalog — post-import muscle-tag review (ingest-report.csv).
-- Reviewed the 404 low-confidence rows: 256 tags confirmed correct, 146 corrected,
-- 2 left ambiguous. This migration applies the 146 PRIMARY corrections to envs
-- where 20260604120200_b1_catalog_seed already ran (the regenerated seed bakes the
-- same corrections in for fresh resets via build-seed.ts PRIMARY_OVERRIDES), then
-- promotes all 402 reviewed-correct rows to is_verified=true. Idempotent; guarded
-- on source='free-exercise-db' so it never touches user- or system-authored rows.
-- 76 of the 146 use codes the coarse->fine mapper cannot emit (obliques/full_body/
-- tibialis): twists & side-bends -> obliques, Olympic lifts -> full_body.

-- 1) primary-tag corrections (146 rows)
update public.exercises e
set primary_muscles = v.prim
from (values
  ('Advanced_Kettlebell_Windmill', array['obliques']::text[]),
  ('Air_Bike', array['obliques']::text[]),
  ('Alternate_Heel_Touchers', array['obliques']::text[]),
  ('Alternating_Hang_Clean', array['full_body']::text[]),
  ('Back_Flyes_-_With_Bands', array['delt_rear']::text[]),
  ('Backward_Medicine_Ball_Throw', array['delt_front']::text[]),
  ('Band_Pull_Apart', array['delt_rear']::text[]),
  ('Barbell_Incline_Shoulder_Raise', array['trap']::text[]),
  ('Barbell_Side_Bend', array['obliques']::text[]),
  ('Battling_Ropes', array['delt_front']::text[]),
  ('Bench_Press_-_Powerlifting', array['pec_lower']::text[]),
  ('Bench_Press_with_Chains', array['pec_lower']::text[]),
  ('Bent_Press', array['obliques']::text[]),
  ('Bent-Knee_Hip_Raise', array['abs_lower']::text[]),
  ('Board_Press', array['pec_lower']::text[]),
  ('Bosu_Ball_Cable_Crunch_With_Side_Bends', array['abs_upper','obliques']::text[]),
  ('Bottoms_Up', array['abs_lower']::text[]),
  ('Box_Jump_Multiple_Response', array['quads','glutes']::text[]),
  ('Box_Skip', array['quads','glutes']::text[]),
  ('Cable_Incline_Triceps_Extension', array['tri_long']::text[]),
  ('Cable_Internal_Rotation', array['delt_front']::text[]),
  ('Cable_Judo_Flip', array['obliques']::text[]),
  ('Cable_Russian_Twists', array['obliques']::text[]),
  ('Car_Deadlift', array['hamstrings','glutes','lower_back']::text[]),
  ('Car_Drivers', array['delt_front']::text[]),
  ('Circus_Bell', array['delt_front']::text[]),
  ('Clean', array['full_body']::text[]),
  ('Clean_and_Jerk', array['full_body']::text[]),
  ('Clean_and_Press', array['full_body']::text[]),
  ('Clean_from_Blocks', array['full_body']::text[]),
  ('Clean_Pull', array['full_body']::text[]),
  ('Cocoons', array['abs_lower']::text[]),
  ('Cross-Body_Crunch', array['obliques','abs_upper']::text[]),
  ('Crossover_Reverse_Lunge', array['quads','glutes']::text[]),
  ('Decline_Dumbbell_Triceps_Extension', array['tri_long']::text[]),
  ('Decline_EZ_Bar_Triceps_Extension', array['tri_long']::text[]),
  ('Decline_Oblique_Crunch', array['obliques']::text[]),
  ('Double_Kettlebell_Alternating_Hang_Clean', array['full_body']::text[]),
  ('Double_Kettlebell_Jerk', array['delt_front']::text[]),
  ('Double_Kettlebell_Snatch', array['full_body']::text[]),
  ('Double_Kettlebell_Windmill', array['obliques']::text[]),
  ('Double_Leg_Butt_Kick', array['hamstrings']::text[]),
  ('Dumbbell_Clean', array['full_body']::text[]),
  ('Dumbbell_Incline_Shoulder_Raise', array['delt_front']::text[]),
  ('Dumbbell_Side_Bend', array['obliques']::text[]),
  ('Elbow_to_Knee', array['obliques']::text[]),
  ('Exercise_Ball_Pull-In', array['abs_lower']::text[]),
  ('External_Rotation', array['delt_rear']::text[]),
  ('External_Rotation_with_Band', array['delt_rear']::text[]),
  ('External_Rotation_with_Cable', array['delt_rear']::text[]),
  ('Flat_Bench_Leg_Pull-In', array['abs_lower']::text[]),
  ('Front_Box_Jump', array['quads']::text[]),
  ('Front_Cable_Raise', array['delt_front']::text[]),
  ('Front_Dumbbell_Raise', array['delt_front']::text[]),
  ('Front_Incline_Dumbbell_Raise', array['delt_front']::text[]),
  ('Front_Plate_Raise', array['delt_front']::text[]),
  ('Front_Two-Dumbbell_Raise', array['delt_front']::text[]),
  ('Handstand_Push-Ups', array['delt_front']::text[]),
  ('Hang_Clean', array['full_body']::text[]),
  ('Hang_Clean_-_Below_the_Knees', array['full_body']::text[]),
  ('Hang_Snatch', array['full_body']::text[]),
  ('Hang_Snatch_-_Below_Knees', array['full_body']::text[]),
  ('Hurdle_Hops', array['glutes','quads']::text[]),
  ('Incline_Barbell_Triceps_Extension', array['tri_long']::text[]),
  ('Internal_Rotation_with_Band', array['delt_front']::text[]),
  ('Isometric_Wipers', array['obliques']::text[]),
  ('Jerk_Balance', array['delt_front']::text[]),
  ('Kettlebell_Figure_8', array['obliques']::text[]),
  ('Kettlebell_Pass_Between_The_Legs', array['obliques']::text[]),
  ('Kettlebell_Pirate_Ships', array['obliques']::text[]),
  ('Kettlebell_Thruster', array['delt_front']::text[]),
  ('Kettlebell_Turkish_Get-Up_Lunge_style', array['delt_front']::text[]),
  ('Kettlebell_Turkish_Get-Up_Squat_style', array['delt_front']::text[]),
  ('Kettlebell_Windmill', array['obliques']::text[]),
  ('Knee_Hip_Raise_On_Parallel_Bars', array['abs_lower']::text[]),
  ('Knee_Tuck_Jump', array['quads']::text[]),
  ('Kneeling_Arm_Drill', array['delt_front']::text[]),
  ('Kneeling_Cable_Crunch_With_Alternating_Oblique_Twists', array['obliques']::text[]),
  ('Landmine_180s', array['obliques']::text[]),
  ('Landmine_Linear_Jammer', array['delt_front']::text[]),
  ('Leg_Pull-In', array['abs_lower']::text[]),
  ('Log_Lift', array['delt_front']::text[]),
  ('Low_Pulley_Row_To_Neck', array['delt_rear']::text[]),
  ('Lower_Back_Curl', array['lower_back']::text[]),
  ('Medicine_Ball_Full_Twist', array['obliques']::text[]),
  ('Medicine_Ball_Scoop_Throw', array['full_body']::text[]),
  ('Muscle_Snatch', array['full_body']::text[]),
  ('Oblique_Crunches', array['obliques']::text[]),
  ('Oblique_Crunches_-_On_The_Floor', array['obliques']::text[]),
  ('One_Arm_Floor_Press', array['pec_lower']::text[]),
  ('One-Arm_High-Pulley_Cable_Side_Bends', array['obliques']::text[]),
  ('One-Arm_Kettlebell_Clean_and_Jerk', array['full_body']::text[]),
  ('One-Arm_Kettlebell_Jerk', array['full_body']::text[]),
  ('One-Arm_Kettlebell_Snatch', array['full_body']::text[]),
  ('One-Arm_Kettlebell_Split_Jerk', array['full_body']::text[]),
  ('One-Arm_Kettlebell_Split_Snatch', array['full_body']::text[]),
  ('One-Arm_Medicine_Ball_Slam', array['obliques']::text[]),
  ('Open_Palm_Kettlebell_Clean', array['full_body']::text[]),
  ('Pallof_Press', array['obliques']::text[]),
  ('Pallof_Press_With_Rotation', array['obliques']::text[]),
  ('Plate_Twist', array['obliques']::text[]),
  ('Power_Clean', array['full_body']::text[]),
  ('Power_Jerk', array['full_body']::text[]),
  ('Power_Snatch', array['full_body']::text[]),
  ('Power_Snatch_from_Blocks', array['full_body']::text[]),
  ('Power_Stairs', array['full_body']::text[]),
  ('Rack_Delivery', array['delt_front']::text[]),
  ('Return_Push_from_Stance', array['delt_front']::text[]),
  ('Reverse_Band_Bench_Press', array['pec_lower']::text[]),
  ('Russian_Twist', array['obliques']::text[]),
  ('Scissor_Kick', array['abs_lower']::text[]),
  ('Seated_Barbell_Twist', array['obliques']::text[]),
  ('Seated_Flat_Bench_Leg_Pull-In', array['abs_lower']::text[]),
  ('Seated_Front_Deltoid', array['delt_front']::text[]),
  ('Seated_Leg_Tucks', array['abs_lower']::text[]),
  ('Seated_Triceps_Press', array['tri_long']::text[]),
  ('Shoulder_Raise', array['trap']::text[]),
  ('Side_Bridge', array['obliques']::text[]),
  ('Side_Jackknife', array['obliques']::text[]),
  ('Single-Arm_Linear_Jammer', array['delt_front']::text[]),
  ('Sledgehammer_Swings', array['obliques']::text[]),
  ('Smith_Machine_Hang_Power_Clean', array['full_body']::text[]),
  ('Smith_Machine_Hip_Raise', array['abs_lower']::text[]),
  ('Snatch', array['full_body']::text[]),
  ('Snatch_from_Blocks', array['full_body']::text[]),
  ('Snatch_Pull', array['full_body']::text[]),
  ('Spell_Caster', array['obliques']::text[]),
  ('Split_Clean', array['full_body']::text[]),
  ('Split_Jerk', array['full_body']::text[]),
  ('Split_Snatch', array['full_body']::text[]),
  ('Squat_Jerk', array['full_body']::text[]),
  ('Standing_Cable_Lift', array['obliques']::text[]),
  ('Standing_Cable_Wood_Chop', array['obliques']::text[]),
  ('Standing_Dumbbell_Straight-Arm_Front_Delt_Raise_Above_Head', array['delt_front']::text[]),
  ('Standing_Front_Barbell_Raise_Over_Head', array['delt_front']::text[]),
  ('Standing_Lateral_Stretch', array['obliques']::text[]),
  ('Standing_One-Arm_Dumbbell_Triceps_Extension', array['tri_long']::text[]),
  ('Stomach_Vacuum', array['abs_lower']::text[]),
  ('Straight_Raises_on_Incline_Bench', array['delt_front']::text[]),
  ('Supine_Chest_Throw', array['pec_lower']::text[]),
  ('Tire_Flip', array['full_body']::text[]),
  ('Torso_Rotation', array['obliques']::text[]),
  ('Two-Arm_Kettlebell_Clean', array['full_body']::text[]),
  ('Two-Arm_Kettlebell_Jerk', array['full_body']::text[]),
  ('Weighted_Ball_Side_Bend', array['obliques']::text[]),
  ('Wind_Sprints', array['glutes','hamstrings','quads']::text[])
) as v(external_id, prim)
where e.external_id = v.external_id and e.source = 'free-exercise-db';

-- 2) verify the 402 reviewed-correct rows (256 confirmed + 146 corrected).
-- The 2 ambiguous rows + the 469 never-flagged rows stay is_verified=false.
update public.exercises
set is_verified = true
where source = 'free-exercise-db' and external_id in (
  '3_4_Sit-Up',
  'Ab_Crunch_Machine',
  'Ab_Roller',
  'Advanced_Kettlebell_Windmill',
  'Air_Bike',
  'Alternate_Heel_Touchers',
  'Alternate_Leg_Diagonal_Bound',
  'Alternating_Deltoid_Raise',
  'Alternating_Floor_Press',
  'Alternating_Hang_Clean',
  'Alternating_Renegade_Row',
  'Arm_Circles',
  'Around_The_Worlds',
  'Atlas_Stone_Trainer',
  'Atlas_Stones',
  'Axle_Deadlift',
  'Back_Flyes_-_With_Bands',
  'Backward_Drag',
  'Backward_Medicine_Ball_Throw',
  'Ball_Leg_Curl',
  'Band_Pull_Apart',
  'Barbell_Ab_Rollout',
  'Barbell_Ab_Rollout_-_On_Knees',
  'Barbell_Bench_Press_-_Medium_Grip',
  'Barbell_Deadlift',
  'Barbell_Full_Squat',
  'Barbell_Guillotine_Bench_Press',
  'Barbell_Incline_Shoulder_Raise',
  'Barbell_Rollout_from_Bench',
  'Barbell_Side_Bend',
  'Barbell_Squat',
  'Barbell_Squat_To_A_Bench',
  'Barbell_Step_Ups',
  'Battling_Ropes',
  'Behind_Head_Chest_Stretch',
  'Bench_Press_-_Powerlifting',
  'Bench_Press_-_With_Bands',
  'Bench_Press_with_Chains',
  'Bent_Over_One-Arm_Long_Bar_Row',
  'Bent_Press',
  'Bent-Arm_Barbell_Pullover',
  'Bent-Arm_Dumbbell_Pullover',
  'Bent-Knee_Hip_Raise',
  'Board_Press',
  'Body_Tricep_Press',
  'Body-Up',
  'Bodyweight_Flyes',
  'Bosu_Ball_Cable_Crunch_With_Side_Bends',
  'Bottoms_Up',
  'Box_Jump_Multiple_Response',
  'Box_Skip',
  'Box_Squat',
  'Box_Squat_with_Bands',
  'Box_Squat_with_Chains',
  'Butt-Ups',
  'Butterfly',
  'Cable_Chest_Press',
  'Cable_Crossover',
  'Cable_Crunch',
  'Cable_Deadlifts',
  'Cable_Incline_Triceps_Extension',
  'Cable_Internal_Rotation',
  'Cable_Iron_Cross',
  'Cable_Judo_Flip',
  'Cable_One_Arm_Tricep_Extension',
  'Cable_Russian_Twists',
  'Cable_Seated_Crunch',
  'Cable_Wrist_Curl',
  'Car_Deadlift',
  'Car_Drivers',
  'Carioca_Quick_Step',
  'Chain_Handle_Extension',
  'Chain_Press',
  'Chest_And_Front_Of_Shoulder_Stretch',
  'Chest_Push_from_3_point_stance',
  'Chest_Push_multiple_response',
  'Chest_Push_single_response',
  'Chest_Push_with_Run_Release',
  'Chest_Stretch_on_Stability_Ball',
  'Circus_Bell',
  'Clean',
  'Clean_and_Jerk',
  'Clean_and_Press',
  'Clean_Deadlift',
  'Clean_from_Blocks',
  'Clean_Pull',
  'Clock_Push-Up',
  'Close-Grip_Barbell_Bench_Press',
  'Close-Grip_Dumbbell_Press',
  'Close-Grip_EZ-Bar_Press',
  'Close-Grip_Push-Up_off_of_a_Dumbbell',
  'Cocoons',
  'Conans_Wheel',
  'Cross_Over_-_With_Bands',
  'Cross-Body_Crunch',
  'Crossover_Reverse_Lunge',
  'Crucifix',
  'Crunch_-_Hands_Overhead',
  'Crunch_-_Legs_On_Exercise_Ball',
  'Crunches',
  'Dead_Bug',
  'Deadlift_with_Bands',
  'Deadlift_with_Chains',
  'Decline_Crunch',
  'Decline_Dumbbell_Triceps_Extension',
  'Decline_EZ_Bar_Triceps_Extension',
  'Decline_Oblique_Crunch',
  'Deficit_Deadlift',
  'Depth_Jump_Leap',
  'Dips_-_Chest_Version',
  'Double_Kettlebell_Alternating_Hang_Clean',
  'Double_Kettlebell_Jerk',
  'Double_Kettlebell_Snatch',
  'Double_Kettlebell_Windmill',
  'Double_Leg_Butt_Kick',
  'Drop_Push',
  'Dumbbell_Bench_Press',
  'Dumbbell_Bench_Press_with_Neutral_Grip',
  'Dumbbell_Clean',
  'Dumbbell_Floor_Press',
  'Dumbbell_Flyes',
  'Dumbbell_Incline_Row',
  'Dumbbell_Incline_Shoulder_Raise',
  'Dumbbell_One-Arm_Triceps_Extension',
  'Dumbbell_One-Arm_Upright_Row',
  'Dumbbell_Raise',
  'Dumbbell_Scaption',
  'Dumbbell_Side_Bend',
  'Dumbbell_Squat',
  'Dumbbell_Squat_To_A_Bench',
  'Dumbbell_Tricep_Extension_-Pronated_Grip',
  'Dynamic_Chest_Stretch',
  'Elbow_Circles',
  'Elbow_to_Knee',
  'Elbows_Back',
  'Exercise_Ball_Crunch',
  'Exercise_Ball_Pull-In',
  'Extended_Range_One-Arm_Kettlebell_Floor_Press',
  'External_Rotation',
  'External_Rotation_with_Band',
  'External_Rotation_with_Cable',
  'Farmers_Walk',
  'Fast_Skipping',
  'Finger_Curls',
  'Flat_Bench_Cable_Flyes',
  'Flat_Bench_Leg_Pull-In',
  'Floor_Press',
  'Floor_Press_with_Chains',
  'Forward_Drag_with_Press',
  'Frankenstein_Squat',
  'Frog_Sit-Ups',
  'Front_Box_Jump',
  'Front_Cable_Raise',
  'Front_Cone_Hops_or_hurdle_hops',
  'Front_Dumbbell_Raise',
  'Front_Incline_Dumbbell_Raise',
  'Front_Plate_Raise',
  'Front_Raise_And_Pullover',
  'Front_Two-Dumbbell_Raise',
  'Goblet_Squat',
  'Gorilla_Chin_Crunch',
  'Handstand_Push-Ups',
  'Hang_Clean',
  'Hang_Clean_-_Below_the_Knees',
  'Hang_Snatch',
  'Hang_Snatch_-_Below_Knees',
  'Heaving_Snatch_Balance',
  'Heavy_Bag_Thrust',
  'Hurdle_Hops',
  'Incline_Barbell_Triceps_Extension',
  'Incline_Push-Up_Close-Grip',
  'Internal_Rotation_with_Band',
  'Iron_Cross',
  'Isometric_Chest_Squeezes',
  'Isometric_Wipers',
  'Jackknife_Sit-Up',
  'Janda_Sit-Up',
  'Jefferson_Squats',
  'Jerk_Balance',
  'JM_Press',
  'Keg_Load',
  'Kettlebell_Dead_Clean',
  'Kettlebell_Figure_8',
  'Kettlebell_Hang_Clean',
  'Kettlebell_Pass_Between_The_Legs',
  'Kettlebell_Pirate_Ships',
  'Kettlebell_Pistol_Squat',
  'Kettlebell_Sumo_High_Pull',
  'Kettlebell_Thruster',
  'Kettlebell_Turkish_Get-Up_Lunge_style',
  'Kettlebell_Turkish_Get-Up_Squat_style',
  'Kettlebell_Windmill',
  'Kipping_Muscle_Up',
  'Knee_Hip_Raise_On_Parallel_Bars',
  'Knee_Tuck_Jump',
  'Kneeling_Arm_Drill',
  'Kneeling_Cable_Crunch_With_Alternating_Oblique_Twists',
  'Kneeling_Cable_Triceps_Extension',
  'Landmine_180s',
  'Landmine_Linear_Jammer',
  'Lateral_Bound',
  'Lateral_Box_Jump',
  'Lateral_Cone_Hops',
  'Leg_Pull-In',
  'Leg-Over_Floor_Press',
  'Leverage_Chest_Press',
  'Log_Lift',
  'Low_Cable_Crossover',
  'Low_Cable_Triceps_Extension',
  'Low_Pulley_Row_To_Neck',
  'Lower_Back_Curl',
  'Lying_Leg_Curls',
  'Machine_Bench_Press',
  'Machine_Triceps_Extension',
  'Medicine_Ball_Chest_Pass',
  'Medicine_Ball_Full_Twist',
  'Medicine_Ball_Scoop_Throw',
  'Muscle_Snatch',
  'Muscle_Up',
  'Narrow_Stance_Squats',
  'Neck_Press',
  'Oblique_Crunches',
  'Oblique_Crunches_-_On_The_Floor',
  'One_Arm_Dumbbell_Bench_Press',
  'One_Arm_Floor_Press',
  'One_Arm_Pronated_Dumbbell_Triceps_Extension',
  'One_Arm_Supinated_Dumbbell_Triceps_Extension',
  'One-Arm_Flat_Bench_Dumbbell_Flye',
  'One-Arm_High-Pulley_Cable_Side_Bends',
  'One-Arm_Kettlebell_Clean',
  'One-Arm_Kettlebell_Clean_and_Jerk',
  'One-Arm_Kettlebell_Floor_Press',
  'One-Arm_Kettlebell_Jerk',
  'One-Arm_Kettlebell_Snatch',
  'One-Arm_Kettlebell_Split_Jerk',
  'One-Arm_Kettlebell_Split_Snatch',
  'One-Arm_Kettlebell_Swings',
  'One-Arm_Medicine_Ball_Slam',
  'One-Arm_Open_Palm_Kettlebell_Clean',
  'One-Arm_Overhead_Kettlebell_Squats',
  'One-Arm_Side_Deadlift',
  'Open_Palm_Kettlebell_Clean',
  'Otis-Up',
  'Overhead_Squat',
  'Overhead_Stretch',
  'Pallof_Press',
  'Pallof_Press_With_Rotation',
  'Palms-Down_Dumbbell_Wrist_Curl_Over_A_Bench',
  'Palms-Down_Wrist_Curl_Over_A_Bench',
  'Palms-Up_Barbell_Wrist_Curl_Over_A_Bench',
  'Palms-Up_Dumbbell_Wrist_Curl_Over_A_Bench',
  'Pin_Presses',
  'Plank',
  'Plate_Twist',
  'Plie_Dumbbell_Squat',
  'Plyo_Kettlebell_Pushups',
  'Plyo_Push-up',
  'Power_Clean',
  'Power_Jerk',
  'Power_Partials',
  'Power_Snatch',
  'Power_Snatch_from_Blocks',
  'Power_Stairs',
  'Press_Sit-Up',
  'Prowler_Sprint',
  'Push_Up_to_Side_Plank',
  'Push-Up_Wide',
  'Push-Ups_-_Close_Triceps_Position',
  'Push-Ups_With_Feet_Elevated',
  'Push-Ups_With_Feet_On_An_Exercise_Ball',
  'Pushups',
  'Pushups_Close_and_Wide_Hand_Positions',
  'Rack_Delivery',
  'Rack_Pull_with_Bands',
  'Rack_Pulls',
  'Return_Push_from_Stance',
  'Reverse_Band_Bench_Press',
  'Reverse_Band_Box_Squat',
  'Reverse_Band_Deadlift',
  'Reverse_Band_Power_Squat',
  'Reverse_Band_Sumo_Deadlift',
  'Reverse_Triceps_Bench_Press',
  'Rickshaw_Carry',
  'Rickshaw_Deadlift',
  'Romanian_Deadlift_from_Deficit',
  'Rope_Climb',
  'Rope_Crunch',
  'Round_The_World_Shoulder_Stretch',
  'Rowing_Stationary',
  'Russian_Twist',
  'Sandbag_Load',
  'Scissor_Kick',
  'Seated_Band_Hamstring_Curl',
  'Seated_Barbell_Twist',
  'Seated_Bent-Over_One-Arm_Dumbbell_Triceps_Extension',
  'Seated_Bent-Over_Two-Arm_Dumbbell_Triceps_Extension',
  'Seated_Dumbbell_Palms-Down_Wrist_Curl',
  'Seated_Dumbbell_Palms-Up_Wrist_Curl',
  'Seated_Flat_Bench_Leg_Pull-In',
  'Seated_Front_Deltoid',
  'Seated_Leg_Curl',
  'Seated_Leg_Tucks',
  'Seated_One-Arm_Dumbbell_Palms-Down_Wrist_Curl',
  'Seated_One-Arm_Dumbbell_Palms-Up_Wrist_Curl',
  'Seated_Overhead_Stretch',
  'Seated_Palm-Up_Barbell_Wrist_Curl',
  'Seated_Palms-Down_Barbell_Wrist_Curl',
  'Seated_Triceps_Press',
  'Seated_Two-Arm_Palms-Up_Low-Pulley_Wrist_Curl',
  'Shoulder_Circles',
  'Shoulder_Raise',
  'Shoulder_Stretch',
  'Side_Bridge',
  'Side_Hop-Sprint',
  'Side_Jackknife',
  'Side_to_Side_Box_Shuffle',
  'Side_To_Side_Chins',
  'Side_Wrist_Pull',
  'Single-Arm_Cable_Crossover',
  'Single-Arm_Linear_Jammer',
  'Single-Arm_Push-Up',
  'Single-Leg_Hop_Progression',
  'Single-Leg_Lateral_Hop',
  'Single-Leg_Stride_Jump',
  'Sit-Up',
  'Skating',
  'Sled_Push',
  'Sledgehammer_Swings',
  'Smith_Incline_Shoulder_Raise',
  'Smith_Machine_Bench_Press',
  'Smith_Machine_Close-Grip_Bench_Press',
  'Smith_Machine_Hang_Power_Clean',
  'Smith_Machine_Hip_Raise',
  'Smith_Machine_One-Arm_Upright_Row',
  'Smith_Machine_Squat',
  'Snatch',
  'Snatch_Balance',
  'Snatch_Deadlift',
  'Snatch_from_Blocks',
  'Snatch_Pull',
  'Speed_Squats',
  'Spell_Caster',
  'Spider_Crawl',
  'Spinal_Stretch',
  'Split_Clean',
  'Split_Jerk',
  'Split_Snatch',
  'Squat_Jerk',
  'Squat_with_Bands',
  'Squat_with_Chains',
  'Squat_with_Plate_Movers',
  'Squats_-_With_Bands',
  'Standing_Bent-Over_One-Arm_Dumbbell_Triceps_Extension',
  'Standing_Bent-Over_Two-Arm_Dumbbell_Triceps_Extension',
  'Standing_Cable_Chest_Press',
  'Standing_Cable_Lift',
  'Standing_Cable_Wood_Chop',
  'Standing_Dumbbell_Straight-Arm_Front_Delt_Raise_Above_Head',
  'Standing_Dumbbell_Triceps_Extension',
  'Standing_Front_Barbell_Raise_Over_Head',
  'Standing_Lateral_Stretch',
  'Standing_Leg_Curl',
  'Standing_Low-Pulley_Deltoid_Raise',
  'Standing_Low-Pulley_One-Arm_Triceps_Extension',
  'Standing_One-Arm_Dumbbell_Triceps_Extension',
  'Standing_Palms-Up_Barbell_Behind_The_Back_Wrist_Curl',
  'Standing_Rope_Crunch',
  'Standing_Towel_Triceps_Extension',
  'Star_Jump',
  'Stomach_Vacuum',
  'Straight_Raises_on_Incline_Bench',
  'Straight-Arm_Dumbbell_Pullover',
  'Stride_Jump_Crossover',
  'Sumo_Deadlift',
  'Sumo_Deadlift_with_Bands',
  'Sumo_Deadlift_with_Chains',
  'Supine_Chest_Throw',
  'Supine_One-Arm_Overhead_Throw',
  'Supine_Two-Arm_Overhead_Throw',
  'Suspended_Fallout',
  'Suspended_Push-Up',
  'Suspended_Split_Squat',
  'Svend_Press',
  'Tate_Press',
  'Tire_Flip',
  'Toe_Touchers',
  'Torso_Rotation',
  'Tricep_Side_Stretch',
  'Triceps_Stretch',
  'Tuck_Crunch',
  'Two-Arm_Kettlebell_Clean',
  'Two-Arm_Kettlebell_Jerk',
  'Upright_Barbell_Row',
  'Upward_Stretch',
  'Weighted_Ball_Side_Bend',
  'Weighted_Crunches',
  'Weighted_Jump_Squat',
  'Weighted_Sit-Ups_-_With_Bands',
  'Wide_Stance_Barbell_Squat',
  'Wide-Grip_Barbell_Bench_Press',
  'Wind_Sprints',
  'Yoke_Walk'
);
