import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

export interface FoodEntry {
  query: string; // FDC search term (hand-authored)
  name_es: string;
  name_en: string;
  category: string;
  fdc_id?: number; // filled by resolve.ts, reviewed before build
  fdc_description?: string; // matched USDA entry text (provenance/review aid)
}
export interface SRFood {
  fdcId: number;
  foodNutrients: { nutrient: { number: string }; amount?: number }[];
}

// USDA SR nutrient numbers (per 100 g). See plan Task 6 header.
const N = {
  kcal: '208',
  protein: '203',
  fat: '204',
  carbs: '205',
  fiber: '291',
  sugar: '269',
  satfat: '606',
} as const;

function round2(n: number): number {
  return Math.round(n * 100) / 100;
}

export function amountFor(food: SRFood, number: string): number | null {
  const fn = food.foodNutrients.find((x) => x.nutrient.number === number);
  return fn?.amount != null ? round2(fn.amount) : null;
}

export function buildRow(entry: FoodEntry, food: SRFood): string {
  const kcal = amountFor(food, N.kcal);
  if (kcal == null) {
    throw new Error(`fdc ${entry.fdc_id} (${entry.name_es}) has no energy value`);
  }
  // U-1: missing sub-macros stay null (never 0 — that would assert "sugar-free").
  const sugar = amountFor(food, N.sugar);
  const satfat = amountFor(food, N.satfat);
  const num = (v: number | null) => (v == null ? 'null' : String(v));
  const esc = (s: string) => s.replace(/'/g, "''");
  // Data-only tuple — the constant is_verified/created_by/source columns live in
  // the INSERT … SELECT (header), keeping this VALUES row free of a null::uuid
  // that VALUES type-inference can't resolve.
  return (
    `      ('${esc(entry.name_es)}', '${esc(entry.name_en)}', 'gram', ` +
    `${kcal}, ${amountFor(food, N.protein) ?? 0}, ${amountFor(food, N.carbs) ?? 0}, ` +
    `${amountFor(food, N.fat) ?? 0}, ${amountFor(food, N.fiber) ?? 0}, ` +
    `${num(sugar)}, ${num(satfat)})`
  );
}

const MIGRATION_HEADER = `-- F-1 step 2/2 — curated whole-foods system seed (generic basics).
-- Generated by scripts/whole-foods/build-seed.ts from scripts/whole-foods/foods.json
-- (USDA SR Legacy via the FDC API). DO NOT hand-edit — re-run the build.
-- Per-row idempotent: each food is inserted only if no source='system' ingredient
-- with the same name already exists, so it is safe to re-run and coexists with
-- the pre-existing 'seed_system_ingredients' rows. STAGED — applied at a checkpoint.

insert into public.ingredients
  (name, name_en, unit_type, kcal_per_unit, protein_g_per_unit,
   carbs_g_per_unit, fat_g_per_unit, fiber_g_per_unit,
   sugar_g_per_unit, saturated_fat_g_per_unit,
   is_verified, created_by_user_id, source)
select v.name, v.name_en, v.unit_type, v.kcal, v.protein, v.carbs, v.fat,
       v.fiber, v.sugar, v.satfat, true, null, 'system'
from (values
`;

const MIGRATION_FOOTER = `
) as v(name, name_en, unit_type, kcal, protein, carbs, fat, fiber, sugar, satfat)
where not exists (
  select 1 from public.ingredients e
  where e.source = 'system' and e.name = v.name
);
`;

const FDC = 'https://api.nal.usda.gov/fdc/v1';

// Batched detail fetch (FDC allows up to 20 ids per /foods call). Returns the
// SRFood-shaped objects buildRow/amountFor already consume.
async function fetchFoods(ids: number[], key: string): Promise<Map<number, SRFood>> {
  const byId = new Map<number, SRFood>();
  for (let i = 0; i < ids.length; i += 20) {
    const batch = ids.slice(i, i + 20);
    const res = await fetch(`${FDC}/foods?api_key=${key}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ fdcIds: batch, format: 'full' }),
    });
    if (!res.ok) throw new Error(`FDC /foods failed: ${res.status}`);
    const foods = (await res.json()) as SRFood[];
    for (const f of foods) byId.set(f.fdcId, f);
  }
  return byId;
}

async function main(): Promise<void> {
  const dir = resolve(import.meta.dirname);
  const foods = JSON.parse(readFileSync(resolve(dir, 'foods.json'), 'utf8')) as FoodEntry[];
  const key = process.env.FDC_API_KEY;
  if (!key) throw new Error('set FDC_API_KEY (free at https://api.data.gov/signup)');

  const unresolved = foods.filter((f) => f.fdc_id == null);
  if (unresolved.length) {
    throw new Error(`run resolve.ts first — ${unresolved.length} entries lack fdc_id`);
  }

  const ids = foods.map((f) => f.fdc_id!);
  const byId = await fetchFoods(ids, key);
  const missing = ids.filter((id) => !byId.has(id));
  if (missing.length) throw new Error(`FDC returned no food for ids: ${missing.join(', ')}`);

  const rows = foods.map((f) => buildRow(f, byId.get(f.fdc_id!)!));
  const sql = MIGRATION_HEADER + rows.join(',\n') + MIGRATION_FOOTER;
  const out = resolve(dir, '../../supabase/migrations/20260523120100_f1_whole_foods_seed.sql');
  writeFileSync(out, sql);
  console.log(`wrote ${rows.length} rows -> ${out}`);
}

// Run main() only when invoked directly, never on import (keeps the test pure).
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  void main();
}
